CREATE TABLE IF NOT EXISTS transaction_main (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    settlement_no VARCHAR(64) NOT NULL COMMENT '核算流水号，用于幂等控制',
    channel VARCHAR(32) NOT NULL COMMENT '交易渠道',
    amount DECIMAL(12,2) NOT NULL COMMENT '交易金额',
    user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
    status VARCHAR(20) NOT NULL COMMENT '交易状态：PENDING-待处理，SUCCESS-成功，FAILED-失败',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uk_settlement_no UNIQUE (settlement_no)
) COMMENT='交易主表'; 